### ISSUE TITLE
libgdiplus

### ISSUE THREAD

**Issue by garethcreaney** [jincod/dotnetcore-buildpack#110]
Calling 3rd party SelectPDF library on Heroku fails on System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies.

```
2020-04-18T17:10:59.530259+00:00 app[web.1]: fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2020-04-18T17:10:59.530300+00:00 app[web.1]: An unhandled exception has occurred while executing the request.
2020-04-18T17:10:59.530301+00:00 app[web.1]: System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
2020-04-18T17:10:59.530310+00:00 app[web.1]: ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
2020-04-18T17:10:59.530311+00:00 app[web.1]: at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
2020-04-18T17:10:59.530311+00:00 app[web.1]: at System.Drawing.SafeNativeMethods.Gdip..cctor()
2020-04-18T17:10:59.530313+00:00 app[web.1]: --- End of inner exception stack trace ---
```

**Comment by jincod** [comment]
Hi @garethcreaney,

I suppose `libgdiplus` doesn't include to default `heroku-18` image. There are two options:
- Use Docker deployment https://devcenter.heroku.com/categories/deploying-with-docker
- Fork this buildpack and add that lib to `bin\compile`

**Comment by garethcreaney** [comment]
Thanks for the feedback. Great buildpack by the way, worked seamlessly on setup. Will try both options and see how I get on. Cheers, Gareth.

**Comment by renerlemes** [comment]
@garethcreaney did you manage to use any of the options to work libgdiplus?
