### ISSUE TITLE
Build success but API not start

### ISSUE THREAD

**Issue by bhaumikpatel** [jincod/dotnetcore-buildpack#120]
I create API project in dotnet core 3.1 in my local working fine but on heroku build also give me success but when I access api it give me error.

**LPJ.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Imgur.API" Version="4.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.5" />
    <PackageReference Include="MongoDB.Driver" Version="2.11.0-beta2" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

</Project>
```

**Build Process Log**
```
Enumerating objects: 173, done.
Counting objects: 100% (173/173), done.
Delta compression using up to 8 threads
Compressing objects: 100% (166/166), done.
Writing objects: 100% (173/173), 43.09 KiB | 1.08 MiB/s, done.
Total 173 (delta 89), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> ASP.NET Core app detected
remote: > Installing dotnet
remote: -----> Removing old cached .NET version
remote: -----> Fetching .NET SDK
remote: -----> Fetching .NET Runtime
remote: -----> Export dotnet to Path
remote: -----> Project File
remote: > /tmp/build_22cb25cc/LPJ.csproj
remote: -----> Project Name
remote: > LPJ
remote: > publish /tmp/build_22cb25cc/LPJ.csproj for Release
remote:
remote: Welcome to .NET Core 3.1!
remote: ---------------------
remote: SDK Version: 3.1.302
remote:
remote: ----------------
remote: Explore documentation: https://aka.ms/dotnet-docs
remote: Report issues and find source on GitHub: https://github.com/dotnet/core
remote: Find out what's new: https://aka.ms/dotnet-whats-new
remote: Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
remote: Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
remote: Write your first app: https://aka.ms/first-net-core-app
remote: --------------------------------------------------------------------------------------
remote: Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
remote: Copyright (C) Microsoft Corporation. All rights reserved.
remote:
remote:   Determining projects to restore...
remote:   Restored /tmp/build_22cb25cc/LPJ.csproj (in 8.66 sec).
remote:   LPJ -> /tmp/build_22cb25cc/bin/Release/netcoreapp3.1/linux-x64/LPJ.dll
remote:   LPJ -> /tmp/build_22cb25cc/heroku_output/
remote:        Add web process to Procfile
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 108.2M
remote: -----> Launching...
remote:        Released v3
remote:        https://lpj-api.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/lpj-api.git
 * [new branch]      master -> master
```
**URL Access https://lpj-api.herokuapp.com/api/values**
```
2020-08-05T04:27:19.312255+00:00 app[web.1]: at LPJ.Program.Main(String[] args) in /tmp/build_22cb25cc/Program.cs:line 12
2020-08-05T04:27:19.392724+00:00 heroku[web.1]: Process exited with status 0
2020-08-05T04:27:19.457632+00:00 heroku[web.1]: State changed from starting to crashed
2020-08-05T04:27:41.000000+00:00 app[api]: Build succeeded
2020-08-05T04:34:33.226916+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/values" host=lpj-api.herokuapp.com request_id=c7677c9f-1a6c-4048-9100-da6be6576f9d fwd="103.226.186.53" dyno= connect= service= status=503 bytes= protocol=https
```
In above API request simple return static string only. No database connection or nothing else. 

**Program.cs**
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace LPJ
{
    public class Program
    {
        public static void Main(string[] args)
        {
            try
            {
                CreateHostBuilder(args).Build().Run();
            }
            catch (System.Exception ex)
            {
                System.Console.Error.WriteLine(ex);
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```

Even I try generate build in my local system it build success fully.
`dotnet publish LPJ.csproj --output ./heroku_output --configuration Release --runtime linux-x64`

**Comment by jincod** [comment]
Hi @bhaumikpatel 

> app[web.1]: at LPJ.Program.Main(String[] args) in /tmp/build_22cb25cc/Program.cs:line 12

Could you share your `Program.cs`?

**Comment by bhaumikpatel** [comment]
I updated main question, on line no 12 have  `CreateHostBuilder(args).Build().Run();`

**Comment by bhaumikpatel** [comment]
I can also provide build project if you want.

**Comment by jincod** [comment]
The build is ok, I see. The problem with the app.
Can you run your release version?
```
cd ./heroku_output
./LPG
```

**Comment by bhaumikpatel** [comment]
I have windows system I don't have linux system.

**Comment by jincod** [comment]
then run `LPG.exe` or `dotnet LPG.dll`

**Comment by bhaumikpatel** [comment]
I execute command **dotnet LPJ.dll**

A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application
was not found in 'E:\Test\LPJ\GITHUB\heroku_output\'.

Failed to run as a self-contained app. If this should be a framework-dependent app, specify the
appropriate framework in E:\Test\LPJ\GITHUB\heroku_output\LPJ.runtimeconfig.json.

**Comment by jincod** [comment]
Try drop the line `<PackageReference Include="Imgur.API" Version="4.0.1" />` from csproj if you don't need

**Comment by jincod** [comment]
Can you restart heroku app and provide full log? 

```
2020-08-05T04:27:19.312255+00:00 app[web.1]: at LPJ.Program.Main(String[] args) in /tmp/build_22cb25cc/Program.cs:line 12
```

we need a stack trace

**Comment by bhaumikpatel** [comment]
Here Full log
```
2020-08-05T04:53:06.516395+00:00 heroku[web.1]: State changed from crashed to starting
2020-08-05T04:53:11.983447+00:00 heroku[web.1]: Starting process with command `cd /app/heroku_output && ./LPJ`
2020-08-05T04:53:14.543430+00:00 heroku[web.1]: Process exited with status 0
2020-08-05T04:53:14.585959+00:00 heroku[web.1]: State changed from starting to crashed
2020-08-05T04:53:14.481129+00:00 app[web.1]: System.PlatformNotSupportedException: EventLog access is not supported on this platform.
2020-08-05T04:53:14.481149+00:00 app[web.1]: at System.Diagnostics.EventLog..ctor(String logName, String machineName, String source)
2020-08-05T04:53:14.481155+00:00 app[web.1]: at Microsoft.Extensions.Logging.EventLog.EventLogSettings.CreateDefaultEventLog()
2020-08-05T04:53:14.481156+00:00 app[web.1]: at Microsoft.Extensions.Logging.EventLog.EventLogSettings.get_EventLog()
2020-08-05T04:53:14.481157+00:00 app[web.1]: at Microsoft.Extensions.Logging.EventLog.EventLogLogger..ctor(String name, EventLogSettings settings, IExternalScopeProvider externalScopeProvider)
2020-08-05T04:53:14.481157+00:00 app[web.1]: at Microsoft.Extensions.Logging.EventLog.EventLogLoggerProvider.CreateLogger(String name)
2020-08-05T04:53:14.481157+00:00 app[web.1]: at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(String categoryName)
2020-08-05T04:53:14.481158+00:00 app[web.1]: at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
2020-08-05T04:53:14.481158+00:00 app[web.1]: at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory factory)
2020-08-05T04:53:14.481158+00:00 app[web.1]: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2020-08-05T04:53:14.481159+00:00 app[web.1]: at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2020-08-05T04:53:14.481172+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2020-08-05T04:53:14.481172+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2020-08-05T04:53:14.481176+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2020-08-05T04:53:14.481179+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2020-08-05T04:53:14.481179+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2020-08-05T04:53:14.481179+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2020-08-05T04:53:14.481180+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2020-08-05T04:53:14.481180+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2020-08-05T04:53:14.481180+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2020-08-05T04:53:14.481180+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2020-08-05T04:53:14.481180+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2020-08-05T04:53:14.481181+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2020-08-05T04:53:14.481181+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2020-08-05T04:53:14.481181+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2020-08-05T04:53:14.481181+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2020-08-05T04:53:14.481181+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2020-08-05T04:53:14.481182+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2020-08-05T04:53:14.481182+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2020-08-05T04:53:14.481182+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
2020-08-05T04:53:14.481182+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2020-08-05T04:53:14.481183+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2020-08-05T04:53:14.481184+00:00 app[web.1]: at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2020-08-05T04:53:14.481185+00:00 app[web.1]: at Microsoft.Extensions.Hosting.HostBuilder.Build()
2020-08-05T04:53:14.481185+00:00 app[web.1]: at LPJ.Program.Main(String[] args) in /tmp/build_22cb25cc/Program.cs:line 12
2020-08-05T05:07:32.066144+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/values**" host=lpj-api.herokuapp.com request_id=aaed6702-50a9-49d4-8351-db9b08361d1f fwd="205.213.114.4" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by bhaumikpatel** [comment]
> Try drop the line `<PackageReference Include="Imgur.API" Version="4.0.1" />` from csproj if you don't need

I did that but same error.

A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application
was not found in 'E:\Test\LPJ\GITHUB\heroku_output\'.

Failed to run as a self-contained app. If this should be a framework-dependent app, specify the
appropriate framework in E:\Test\LPJ\GITHUB\heroku_output\LPJ.runtimeconfig.json.

**Comment by jincod** [comment]
```
2020-08-05T04:53:14.481129+00:00 app[web.1]: System.PlatformNotSupportedException: EventLog access is not supported on this platform.
2020-08-05T04:53:14.481149+00:00 app[web.1]: at System.Diagnostics.EventLog..ctor(String logName, String machineName, String source)
2020-08-05T04:53:14.481155+00:00 app[web.1]: at Microsoft.Extensions.Logging.EventLog.EventLogSettings.CreateDefaultEventLog()
```

So, this is a app problem, not buildpack.

Check you `Configure(IApplicationBuilder app)` method and drop the line about EventLog logging or from `appSettings.json`. It is windows related part and doesn't work on Unix.
