### ISSUE TITLE
Project builds, then I get error when I try to access

### ISSUE THREAD

**Issue by sbrevolution5** [jincod/dotnetcore-buildpack#144]
Whenever I try to access my blazor server project, this happens:
```
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
2021-09-07T17:39:32.536764+00:00 app[web.1]:       Connection id "0HMBI4I8RGNTB", Request id "0HMBI4I8RGNTB:00000002": An unhandled exception was thrown by the application.
2021-09-07T17:39:32.536778+00:00 app[web.1]:       System.NullReferenceException: Object reference not set to an instance of an object.
2021-09-07T17:39:32.536779+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderConfigurationExtensions.<>c.<AddSigningCredentials>b__10_2(IServiceProvider sp)
2021-09-07T17:39:32.536790+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536802+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2021-09-07T17:39:32.536813+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536813+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-09-07T17:39:32.536824+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536834+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2021-09-07T17:39:32.536835+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536872+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-09-07T17:39:32.536883+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536883+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536894+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-09-07T17:39:32.536905+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536905+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536916+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-09-07T17:39:32.536927+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536927+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536938+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-09-07T17:39:32.536949+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536950+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536961+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-09-07T17:39:32.536972+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536972+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-09-07T17:39:32.536983+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-09-07T17:39:32.536983+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2021-09-07T17:39:32.536994+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2021-09-07T17:39:32.537005+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2021-09-07T17:39:32.537006+00:00 app[web.1]:          at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2021-09-07T17:39:32.537017+00:00 app[web.1]:          at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.AuthenticateAsync(HttpContext context, String scheme)
2021-09-07T17:39:32.537018+00:00 app[web.1]:          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2021-09-07T17:39:32.537018+00:00 app[web.1]:          at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
2021-09-07T17:39:32.537029+00:00 app[web.1]:          at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
2021-09-07T17:39:32.537029+00:00 app[web.1]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-09-07T17:39:32.537040+00:00 app[web.1]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
2021-09-07T17:39:32.537050+00:00 app[web.1]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-09-07T17:39:32.537051+00:00 app[web.1]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2021-09-07T17:39:32.536170+00:00 heroku[router]: at=info method=GET path="/" host=cheflistapp.herokuapp.com request_id=1e303050-f6f3-4649-babd-8d87d0a99741 fwd="71.150.209.189" dyno=web.1 connect=0ms service=10ms status=500 bytes=130 protocol=https```

**Comment by nbarbettini** [comment]
An error involving `IdentityServerBuilderConfigurationExtensions.AddSigningCredentials` makes me suspect that something is missing from your configuration.

Does the application run locally, especially if you set `ASPNETCORE_ENVIRONMENT=Production`?

**Comment by sbrevolution5** [comment]
It doesn't, and oddly enough if I change the environment to development in heroku it runs.  It appears to be an issue with the certificate, and this is something that seems FAR beyond my skillset.  I've managed to create a certificate, and attempt to use it to run the app, but the problem is that now it won't launch in either configuration

**Comment by sbrevolution5** [comment]
It seems like if I'm using the hobby tier on heroku, it would generate a certificate, but I need to be able to get that certificate in my code for the addsigning credentials method, and I don't know where to find it once I'm on the heroku server

**Comment by nbarbettini** [comment]
I'm not familiar with what `AddSigningCredentials` does in IdentityServer. What certificate are you trying to use?

**Comment by sbrevolution5** [comment]
I honestly don't know, but it appears that without one I can't do anything, from what I've been able to gather, of course no one else seems to have ever hosted a blazor app on heroku, at least not thats run into this issue

**Comment by sbrevolution5** [comment]
Ok, I had a issue with my local build where my database connection string had been changed (by me).  It now builds in production locally, but of course, nothing changed on the heroku end
