### ISSUE TITLE
Throws Exception on Heroku, but local it works

### ISSUE THREAD

**Issue by BlueLemon1** [jincod/dotnetcore-buildpack#60]
Hello,

i get following thrown exception on Heroku, but if i use exactly the same on my local machine (Windows10) , no such error is thrown. does it handle files differently?
can you maybe help me please
`Unhandled Exception: Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at MightyBotCore.utils.Database..ctor() in /tmp/build_ab0f0b852ec752f5c6096a30698256be/MightyBotCore/utils/Database.cs:line 31
   at MightyBotCore.Program.<StartAsync>d__3.MoveNext() in /tmp/build_ab0f0b852ec752f5c6096a30698256be/MightyBotCore/Startup.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MightyBotCore.Program.Main(String[] args) in /tmp/build_ab0f0b852ec752f5c6096a30698256be/MightyBotCore/Startup.cs:line 15`

**Comment by jincod** [comment]
Hi @BlueLemon1,

I think this is your case https://github.com/dotnet/corefx/issues/11042

If I understood correctly this method try to write `*.pem` file on FIleSytem, but Heroku doesn't allow to write on FS after deployment

**Comment by BlueLemon1** [comment]
hi again @jincod 

to my understanding
it is not really writing to FS , but its loading an key.p12 file and seems to not find it.

**Comment by BlueLemon1** [comment]
thanks for ur help!
i managed to fix it.
My path to this key.p12 was hardcoded like "cfg\key.p12".
But Ubuntu seems to work a bit different.
Working with Path.Combine() worked out.
Thanks for your help tho and sorry for taking your time !
